<a href="https://colab.research.google.com/github/AaronGaribay/datacademy2021/blob/main/algebra%20lineal/1_2_Dimension_de_escalar_vector_o_matriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4]])
tensor = np.array([
    [[1,2,3],[4,5,6],[6,7,8]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
])

In [3]:
escalar

5.679

In [5]:
print(vector, vector.shape)

[1 2 3] (3,)


In [6]:
print(matriz, matriz.shape)

[[1 2]
 [3 4]] (2, 2)


In [7]:
matriz.size

4

In [8]:
print(tensor, tensor.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 6  7  8]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]] (3, 3, 3)


In [9]:
tensor.size

27