<a href="https://colab.research.google.com/github/AaronGaribay/datacademy2021/blob/main/algebra%20lineal/2_2_Traspocicion_y_suma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [12]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
])

In [5]:
print(vector, vector.T)

[1 2 3] [1 2 3]


In [8]:
print(matriz, end='\n\n')
print(matriz.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [13]:
print(tensor, end='\n\n')
print(tensor.T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]]


Operaciones de matrices

In [14]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[1,2], [3,4], [5,6]])
A + B

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [15]:
A + escalar

array([[ 6.679,  7.679],
       [ 8.679,  9.679],
       [10.679, 11.679]])