<a href="https://colab.research.google.com/github/AaronGaribay/datacademy2021/blob/main/algebra%20lineal/3_1_producto_interno_entre_una_matriz_y_un_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2], [3,4], [5,6]])

In [5]:
A = matriz * vector

In [6]:
# Producto interno 
B = matriz.dot(vector)

In [7]:
A

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

In [8]:
B

array([ 8, 18, 28])

In [9]:
vector * matriz

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])