<a href="https://colab.research.google.com/github/AaronGaribay/datacademy2021/blob/main/algebra%20lineal/examen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
vector = [1/2, 1/2, 1/2, 1/2]
vector = np.array(vector)
vector

array([0.5, 0.5, 0.5, 0.5])

In [ ]:
np.linalg.norm(vector, ord=2)

1.0

In [ ]:
M1 = [
      [1,2],
      [3,4],
      [5,6]
      ]
M1 = np.array(M1)
M2 = [
      [34, 42, 123],
      [123, 981, 32]
      ]
M2 = np.array(M2)

In [ ]:
print(np.dot(M1, M2))
print(np.dot(M2,M1))

[[ 280 2004  187]
 [ 594 4050  497]
 [ 908 6096  807]]
[[ 775  974]
 [3226 4362]]


In [ ]:
v=[7,-7,3]
u=[1,1,0]
w=[0,0,1]
v = np.array(v)
u = np.array(u)
w = np.array(w)


In [ ]:
np.dot(v,u)

0

In [ ]:
M = [[1, 0, 0, 0, 0],
[0, 2, 0, 0, 0],
[0, 0, 3, 0, 0],
[0, 0, 0, 4, 0],
[0, 0, 0, 0, 5]]

M = np.array(M)

In [ ]:
np.linalg.det(M)

119.99999999999997

In [ ]:
M = [[1, 2, 3, 4], [5, 6, 7, 8], [9,10, 11,12]]
M = np.array(M)
M.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
M = [[1 ,3], [5, 6]]
M = np.array(M)

In [ ]:
M + 3

array([[4, 6],
       [8, 9]])

In [ ]:
M + np.array([[3],[3]])

array([[4, 6],
       [8, 9]])